# Generated by Django 4.2.7 on 2023-11-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0002_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
