# Generated by Django 4.2.7 on 2023-11-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0002_alter_city_city_name_alter_user_city'),
        ('tambolaapp', '0003_alter_user_mobile_no'),
    ]

    operations = [
    ]
