# Generated by Django 4.2.7 on 2023-11-21 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0004_merge_20231120_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Game_Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_ticket', models.FileField(default='ticket/sample.png', upload_to='ticket')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('description', models.TextField()),
                ('amount', models.CharField(max_length=50, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
