# Generated by Django 4.2.7 on 2023-11-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0004_merge_20231121_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='settings.MEDIA_ROOT/profile/user.png', upload_to='profile'),
        ),
    ]
