# Generated by Django 4.2.7 on 2023-11-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0005_user_otp_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='profile/user.png', upload_to='profile'),
        ),
    ]
