# Generated by Django 4.2.7 on 2023-11-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0007_newgame_alter_user_mobile_no_ruleingame_newgame_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user',
            table='customer',
        ),
    ]
