# Generated by Django 4.2.7 on 2023-11-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0007_game_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_rule',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='game_rule',
            name='is_used',
        ),
        migrations.AddField(
            model_name='game_rule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
