# Generated by Django 4.2.7 on 2023-11-21 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0008_remove_game_rule_amount_remove_game_rule_is_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100, null=True, unique=True)),
                ('message_for_player', models.TextField()),
                ('lobby', models.CharField(max_length=50, null=True)),
                ('ticket_cost', models.CharField(max_length=50)),
                ('start_at', models.DateTimeField()),
                ('ticket_request_till', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
