# Generated by Django 4.2.7 on 2023-11-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0009_remove_game_rule_name_newgame_timer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_rule',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game_rule',
            name='sample_ticket',
            field=models.ImageField(default='ticket/sample.png', upload_to='ticket'),
        ),
    ]
