# Generated by Django 4.2.7 on 2023-11-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0009_newgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgame',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
