# Generated by Django 4.2.7 on 2023-11-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0010_game_rule_name_alter_game_rule_sample_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_rule',
            name='sample_ticket',
            field=models.FileField(default='ticket/sample.png', upload_to='ticket'),
        ),
    ]
