# Generated by Django 4.2.7 on 2023-11-21 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0010_newgame_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField()),
                ('number_of_tickets', models.CharField(max_length=50, null=True)),
                ('total_cost', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tambolaapp.newgame')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tambolaapp.game_rule')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
