# Generated by Django 4.2.7 on 2023-11-23 06:00

from django.db import migrations, models
import tambolaapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0011_alter_game_rule_sample_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='9WESE2B', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='profile/user.png', upload_to=tambolaapp.models.filepath_profile),
        ),
        migrations.AddField(
            model_name='user',
            name='refer_by',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='refer_code',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='game_rule',
            name='sample_ticket',
            field=models.FileField(default='ticket/sample.png', upload_to=tambolaapp.models.filepath),
        ),
    ]
