# Generated by Django 4.2.7 on 2023-11-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0011_ruleingame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleingame',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
