# Generated by Django 4.2.7 on 2023-11-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0012_user_my_code_user_otp_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='0xbqxc', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='ZFHYSED', max_length=100),
        ),
    ]
