# Generated by Django 4.2.7 on 2023-11-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0012_alter_ruleingame_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgame',
            name='number_of_tickets',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
