# Generated by Django 4.2.7 on 2023-11-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0013_newgame_number_of_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refer_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refer_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
