# Generated by Django 4.2.7 on 2023-11-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0014_remove_page_user_alter_newgame_private_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='u20odh', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='BMKMHHT', max_length=100),
        ),
    ]
