# Generated by Django 4.2.7 on 2023-11-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0015_alter_user_refer_by_alter_user_refer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgame',
            name='timer',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
