# Generated by Django 4.2.7 on 2023-11-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0016_newgame_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='ticket_cost',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
