# Generated by Django 4.2.7 on 2023-11-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0017_page_created_at_page_user_alter_newgame_private_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='user',
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='5waaj4', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='D081UX7', max_length=100),
        ),
    ]
