# Generated by Django 4.2.7 on 2023-11-25 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0018_remove_page_user_alter_newgame_private_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='ibmf2r', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='VKGES15', max_length=100),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(default=[])),
                ('is_winner', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('assign_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambolaapp.newgame')),
            ],
        ),
        migrations.CreateModel(
            name='BuyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now=True)),
                ('order_status', models.BooleanField(default=False)),
                ('order_price', models.CharField(max_length=200, null=True)),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('ticketid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambolaapp.ticket')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
