# Generated by Django 4.2.7 on 2023-11-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0019_alter_newgame_private_code_alter_user_my_code_ticket_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paybywalletamount',
            old_name='walletid',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='k5vycs', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='L0851H0', max_length=100),
        ),
    ]
