# Generated by Django 4.2.7 on 2023-11-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0019_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
