# Generated by Django 4.2.7 on 2023-11-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0020_rename_walletid_paybywalletamount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='6jtu6p', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='32G3ZGB', max_length=100),
        ),
        migrations.DeleteModel(
            name='AddMoney',
        ),
    ]
