# Generated by Django 4.2.7 on 2023-11-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0025_paybywalletamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='JXCESIK', max_length=100),
        ),
    ]
