# Generated by Django 4.2.7 on 2023-11-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0026_user_my_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='0h2cz7', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='6TSJJ7G', max_length=100),
        ),
    ]
