# Generated by Django 4.2.7 on 2023-11-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0027_newgame_private_code_alter_user_my_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[27, 62, 47, 38, 56, 19, 20, 55, 40, 17, 74, 85, 24, 10, 64, 52, 26, 29, 32, 60, 13, 37, 75, 82, 18, 51, 5, 8, 71, 59, 80, 39, 28, 44, 49, 45, 21, 84, 1, 70, 3, 36, 58, 57, 4, 79, 15, 65, 72, 81, 53, 69, 46, 35, 89, 25, 16, 76, 23, 31, 73, 30, 67, 14, 86, 88, 43, 66, 22, 83, 87, 42, 34, 41, 68, 7, 33, 77, 54, 78, 6, 9, 50, 2, 63, 48, 90, 12, 61, 11]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='s6seto', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='IKCP6C7', max_length=100),
        ),
    ]
