# Generated by Django 4.2.7 on 2023-11-24 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0028_newgame_game_counter_alter_newgame_private_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[45, 47, 33, 13, 65, 10, 30, 90, 81, 49, 19, 40, 67, 25, 1, 16, 50, 56, 61, 76, 2, 31, 32, 85, 35, 52, 66, 55, 83, 12, 69, 79, 57, 82, 70, 11, 34, 42, 28, 23, 7, 64, 3, 38, 84, 46, 24, 4, 71, 5, 80, 21, 86, 60, 74, 54, 41, 73, 48, 27, 78, 36, 63, 18, 39, 29, 44, 77, 75, 58, 43, 37, 62, 14, 9, 26, 22, 6, 20, 15, 72, 68, 17, 51, 59, 87, 89, 8, 53, 88]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='2rsug2', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='VBA06LZ', max_length=100),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(default=[])),
                ('is_winner', models.BooleanField(default=False)),
                ('assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambolaapp.newgame')),
            ],
        ),
    ]
