# Generated by Django 4.2.7 on 2023-11-24 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0029_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[8, 85, 25, 6, 61, 34, 86, 41, 37, 44, 48, 77, 28, 57, 30, 36, 35, 27, 59, 73, 71, 60, 87, 42, 14, 70, 32, 20, 31, 79, 62, 49, 43, 90, 69, 67, 26, 33, 64, 24, 39, 46, 55, 54, 47, 68, 11, 40, 4, 13, 76, 83, 12, 15, 88, 5, 50, 81, 23, 38, 80, 16, 1, 89, 17, 65, 75, 19, 52, 53, 18, 51, 7, 63, 78, 3, 82, 74, 66, 29, 45, 9, 22, 84, 10, 21, 58, 72, 2, 56]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='lay078', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assign_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='K731HUR', max_length=100),
        ),
    ]
