# Generated by Django 4.2.7 on 2023-11-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0030_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[49, 7, 33, 80, 6, 71, 8, 23, 58, 15, 66, 75, 19, 10, 89, 81, 24, 40, 13, 57, 53, 77, 65, 28, 27, 47, 64, 43, 41, 61, 51, 26, 42, 2, 59, 32, 31, 84, 44, 70, 34, 88, 17, 76, 68, 25, 74, 55, 39, 21, 3, 14, 30, 37, 35, 90, 62, 4, 69, 52, 85, 83, 72, 50, 60, 79, 9, 12, 73, 1, 38, 20, 29, 86, 82, 16, 22, 48, 46, 78, 67, 45, 18, 36, 54, 87, 11, 56, 63, 5]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='ew4mfr', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='42P3UFW', max_length=100),
        ),
    ]
