# Generated by Django 4.2.7 on 2023-11-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0031_ticket_is_paid_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[51, 25, 48, 7, 3, 68, 32, 52, 28, 6, 58, 71, 8, 56, 37, 18, 83, 1, 84, 31, 77, 54, 36, 86, 10, 75, 60, 73, 69, 72, 20, 21, 24, 89, 14, 59, 47, 38, 12, 26, 79, 88, 15, 76, 67, 46, 65, 81, 63, 87, 61, 30, 43, 45, 23, 9, 66, 70, 35, 44, 39, 80, 85, 16, 74, 33, 41, 17, 34, 22, 78, 5, 13, 90, 4, 42, 11, 2, 50, 55, 29, 57, 62, 82, 40, 49, 64, 27, 19, 53]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='0dvel0', max_length=100),
        ),
        migrations.AlterField(
            model_name='paybywalletamount',
            name='walletid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambolaapp.walletamt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='R6BIMM8', max_length=100),
        ),
    ]
