# Generated by Django 4.2.7 on 2023-11-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0032_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgame',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[54, 72, 46, 77, 67, 19, 64, 65, 57, 55, 40, 1, 21, 11, 30, 31, 33, 14, 47, 48, 89, 86, 6, 24, 78, 60, 58, 56, 28, 15, 68, 45, 5, 7, 43, 12, 81, 69, 52, 80, 88, 25, 22, 85, 59, 20, 49, 66, 87, 75, 4, 27, 35, 44, 61, 13, 29, 74, 53, 63, 50, 23, 62, 34, 18, 90, 41, 39, 10, 32, 73, 82, 26, 42, 38, 79, 37, 83, 71, 2, 76, 8, 16, 51, 70, 17, 3, 84, 9, 36]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='11d9bu', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='ULKLG2C', max_length=100),
        ),
    ]
