# Generated by Django 4.2.7 on 2023-11-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0033_newgame_is_started_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newgame',
            name='is_started',
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[19, 73, 50, 42, 25, 62, 84, 32, 86, 64, 79, 44, 52, 5, 48, 16, 68, 80, 51, 90, 83, 3, 1, 9, 21, 72, 67, 55, 36, 45, 13, 6, 39, 14, 30, 11, 61, 77, 33, 20, 8, 85, 24, 88, 12, 41, 10, 22, 7, 28, 75, 38, 60, 89, 37, 87, 69, 43, 54, 66, 23, 31, 59, 78, 57, 49, 2, 58, 53, 35, 27, 81, 29, 34, 74, 47, 65, 76, 40, 46, 18, 56, 4, 15, 63, 26, 82, 70, 17, 71]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='vms099', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='4R3XMZY', max_length=100),
        ),
    ]
