# Generated by Django 4.2.7 on 2023-11-25 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0034_remove_newgame_is_started_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[58, 45, 65, 29, 90, 34, 72, 63, 66, 39, 83, 24, 89, 36, 38, 20, 30, 60, 42, 3, 69, 43, 6, 23, 76, 2, 62, 28, 13, 41, 21, 10, 40, 85, 12, 18, 48, 56, 55, 33, 26, 47, 37, 19, 9, 1, 57, 25, 86, 35, 46, 67, 61, 64, 81, 5, 79, 71, 78, 82, 53, 7, 87, 14, 32, 15, 88, 73, 80, 11, 17, 27, 70, 22, 54, 74, 77, 8, 50, 44, 4, 51, 16, 68, 75, 59, 49, 31, 84, 52]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='zb2dsw', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='Q2EPEHT', max_length=100),
        ),
        migrations.CreateModel(
            name='Compliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('compliment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliment_by', to=settings.AUTH_USER_MODEL)),
                ('compliment_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliment_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
