# Generated by Django 4.2.7 on 2023-11-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0035_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_created',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='game_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='game_won',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[13, 85, 29, 41, 31, 8, 35, 81, 88, 68, 38, 20, 54, 84, 23, 66, 4, 3, 44, 24, 15, 62, 40, 30, 83, 16, 82, 70, 58, 50, 89, 63, 19, 53, 87, 7, 2, 69, 52, 39, 9, 33, 12, 64, 59, 74, 26, 25, 10, 75, 80, 76, 5, 48, 47, 79, 60, 78, 55, 86, 17, 27, 32, 51, 11, 1, 77, 90, 45, 61, 6, 46, 22, 73, 71, 49, 57, 65, 37, 42, 34, 43, 67, 56, 21, 72, 14, 28, 36, 18]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='1ekk7f', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='KFBJN1L', max_length=100),
        ),
    ]
