# Generated by Django 4.2.7 on 2023-11-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0036_user_game_created_user_game_played_user_game_won_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='game_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='game_played',
        ),
        migrations.RemoveField(
            model_name='user',
            name='game_won',
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[35, 28, 73, 69, 21, 43, 85, 46, 14, 5, 23, 11, 16, 18, 8, 33, 48, 17, 32, 68, 64, 80, 53, 55, 27, 54, 57, 3, 75, 86, 19, 22, 90, 44, 12, 63, 45, 51, 78, 49, 42, 74, 82, 60, 67, 38, 30, 84, 6, 72, 66, 36, 1, 79, 40, 39, 26, 56, 31, 24, 20, 10, 62, 61, 50, 76, 41, 89, 34, 13, 47, 65, 59, 25, 29, 77, 37, 81, 71, 58, 70, 88, 15, 83, 52, 9, 2, 4, 7, 87]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='p64ntq', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='7F2VVR7', max_length=100),
        ),
    ]
