# Generated by Django 4.2.7 on 2023-11-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0037_remove_user_game_created_remove_user_game_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paybywalletamount',
            name='walletid',
        ),
        migrations.AddField(
            model_name='paybywalletamount',
            name='amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[61, 35, 19, 39, 65, 83, 85, 29, 14, 53, 34, 78, 13, 11, 55, 44, 90, 5, 40, 87, 20, 45, 26, 38, 54, 50, 52, 72, 70, 31, 77, 89, 74, 46, 12, 33, 4, 10, 6, 1, 15, 63, 43, 42, 80, 84, 41, 36, 25, 64, 51, 76, 9, 21, 16, 75, 47, 73, 18, 79, 17, 3, 56, 49, 88, 8, 69, 59, 71, 23, 30, 62, 67, 27, 37, 48, 60, 7, 57, 68, 66, 32, 2, 81, 82, 24, 28, 22, 86, 58]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='c4pw84', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='5929LFW', max_length=100),
        ),
    ]
