# Generated by Django 4.2.7 on 2023-11-27 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0038_remove_paybywalletamount_walletid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[41, 48, 22, 84, 29, 25, 87, 1, 31, 21, 88, 59, 35, 75, 64, 58, 20, 32, 61, 39, 79, 44, 81, 43, 54, 4, 83, 65, 66, 24, 90, 2, 86, 51, 82, 27, 46, 9, 8, 3, 70, 6, 57, 14, 19, 17, 89, 34, 71, 38, 28, 36, 73, 62, 52, 60, 18, 78, 5, 15, 67, 80, 40, 26, 10, 7, 72, 55, 69, 50, 49, 37, 11, 47, 74, 33, 13, 63, 30, 85, 56, 23, 42, 12, 16, 68, 76, 45, 53, 77]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='h0kef5', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='4HFLSMC', max_length=100),
        ),
        migrations.CreateModel(
            name='ClaimRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_array', models.JSONField(default=[])),
                ('check_claim', models.BooleanField(default=False)),
                ('claim_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambolaapp.newgame')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambolaapp.game_rule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
