# Generated by Django 4.2.7 on 2023-11-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0039_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[71, 61, 32, 90, 9, 15, 13, 35, 20, 23, 76, 34, 26, 57, 37, 2, 5, 1, 51, 25, 85, 21, 12, 11, 65, 62, 52, 36, 27, 49, 4, 66, 38, 55, 89, 43, 67, 64, 81, 47, 58, 74, 3, 83, 22, 46, 6, 40, 48, 45, 8, 19, 59, 77, 16, 18, 53, 14, 63, 86, 80, 30, 79, 54, 88, 56, 70, 39, 31, 28, 24, 82, 50, 75, 73, 72, 10, 84, 68, 44, 41, 7, 60, 78, 33, 17, 69, 87, 29, 42]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='07xkcj', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='8A0GH3U', max_length=100),
        ),
    ]
