# Generated by Django 4.2.7 on 2023-11-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0040_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_registration_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[41, 55, 10, 33, 85, 25, 60, 19, 77, 40, 75, 8, 46, 28, 50, 53, 76, 83, 36, 74, 26, 63, 27, 29, 72, 32, 12, 49, 43, 64, 70, 84, 9, 23, 79, 39, 73, 67, 81, 57, 13, 5, 52, 58, 11, 54, 82, 65, 31, 7, 61, 48, 66, 78, 22, 1, 44, 71, 45, 3, 51, 21, 37, 89, 18, 68, 90, 17, 86, 59, 88, 38, 20, 35, 34, 69, 56, 14, 4, 2, 80, 62, 47, 6, 15, 24, 87, 30, 42, 16]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='50x7qs', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='JQG49AW', max_length=100),
        ),
    ]
