# Generated by Django 4.2.7 on 2023-11-27 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0041_user_device_registration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[31, 10, 85, 88, 61, 2, 58, 24, 44, 42, 16, 45, 62, 22, 82, 43, 72, 32, 71, 87, 59, 28, 11, 49, 52, 14, 21, 23, 47, 73, 69, 81, 53, 26, 38, 29, 89, 13, 37, 18, 15, 19, 83, 17, 57, 74, 90, 34, 63, 9, 25, 55, 70, 64, 27, 68, 6, 1, 75, 41, 4, 77, 5, 86, 20, 67, 7, 84, 66, 8, 65, 80, 40, 78, 46, 54, 3, 56, 33, 79, 50, 39, 76, 48, 30, 36, 51, 35, 12, 60]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='0mzrex', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='WU0UFW4', max_length=100),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('image', models.FileField(default='notification/notification.png', upload_to='notification')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
