# Generated by Django 4.2.7 on 2023-11-27 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0042_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[34, 24, 76, 42, 2, 69, 73, 28, 80, 18, 13, 61, 4, 10, 30, 65, 1, 54, 32, 66, 51, 60, 58, 77, 16, 9, 27, 23, 26, 87, 56, 41, 38, 44, 52, 67, 72, 36, 79, 21, 86, 59, 7, 25, 3, 82, 75, 74, 12, 20, 43, 48, 62, 35, 68, 40, 31, 57, 89, 71, 50, 53, 14, 83, 45, 81, 49, 85, 22, 47, 17, 33, 6, 15, 90, 78, 29, 88, 5, 37, 84, 64, 63, 8, 55, 19, 70, 39, 11, 46]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='j17crr', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='CX63K8S', max_length=100),
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
