# Generated by Django 4.2.7 on 2023-11-28 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0043_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[40, 15, 7, 34, 65, 61, 76, 51, 69, 73, 54, 29, 3, 63, 79, 22, 23, 52, 33, 56, 43, 45, 9, 49, 59, 80, 11, 27, 53, 28, 17, 13, 35, 31, 30, 66, 86, 6, 16, 90, 26, 60, 75, 10, 58, 38, 78, 50, 82, 19, 25, 8, 67, 4, 89, 81, 55, 64, 14, 44, 71, 72, 57, 85, 39, 46, 47, 41, 18, 77, 84, 70, 42, 48, 32, 12, 87, 21, 1, 36, 5, 24, 68, 74, 20, 83, 2, 62, 37, 88]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='bs9p7s', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='88ZD03Y', max_length=100),
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(max_length=200)),
                ('bank_account_holder_name', models.CharField(max_length=200)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
