# Generated by Django 4.2.7 on 2023-11-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0044_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrule',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tambolaapp.ticket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[58, 29, 66, 20, 60, 39, 18, 6, 19, 24, 13, 81, 37, 83, 78, 70, 35, 31, 63, 26, 42, 85, 72, 61, 50, 57, 49, 27, 68, 90, 32, 38, 8, 17, 56, 25, 73, 45, 71, 87, 48, 80, 40, 84, 53, 22, 65, 47, 52, 4, 14, 59, 9, 79, 30, 11, 33, 21, 89, 7, 74, 5, 23, 3, 69, 54, 41, 55, 12, 88, 62, 34, 76, 75, 82, 36, 64, 46, 44, 1, 43, 77, 67, 10, 16, 51, 86, 2, 28, 15]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='fq86ak', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='DAE2DYN', max_length=100),
        ),
    ]
