# Generated by Django 4.2.7 on 2023-11-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0045_claimrule_ticket_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[44, 64, 58, 83, 59, 23, 69, 40, 32, 46, 55, 54, 75, 42, 14, 85, 33, 61, 73, 51, 76, 24, 81, 31, 79, 3, 49, 65, 27, 87, 71, 21, 38, 41, 62, 35, 5, 66, 80, 43, 1, 16, 4, 60, 37, 78, 22, 17, 86, 18, 67, 89, 12, 52, 13, 53, 6, 36, 8, 28, 82, 56, 57, 90, 15, 72, 34, 20, 7, 74, 29, 77, 2, 50, 84, 88, 10, 39, 11, 63, 25, 47, 68, 45, 26, 19, 48, 9, 30, 70]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='z22lxf', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='4AFFESN', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='claimrule',
            unique_together={('rule', 'ticket')},
        ),
    ]
