# Generated by Django 4.2.7 on 2023-11-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0046_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[77, 2, 7, 76, 54, 82, 29, 60, 9, 57, 72, 53, 78, 37, 14, 39, 51, 49, 6, 18, 89, 33, 83, 59, 10, 70, 84, 62, 36, 88, 41, 45, 31, 47, 21, 80, 3, 46, 40, 86, 35, 28, 52, 55, 85, 11, 38, 42, 16, 23, 90, 63, 73, 75, 19, 22, 69, 20, 64, 27, 79, 74, 15, 13, 32, 48, 34, 58, 30, 44, 24, 50, 87, 25, 26, 1, 56, 17, 43, 65, 5, 81, 8, 68, 66, 61, 4, 12, 67, 71]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='x0vmyd', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='E8Z5SGP', max_length=100),
        ),
    ]
