# Generated by Django 4.2.7 on 2023-11-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0047_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pattern',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[38, 3, 45, 60, 52, 49, 55, 25, 61, 81, 16, 51, 34, 23, 78, 44, 65, 86, 63, 87, 4, 35, 9, 27, 71, 5, 15, 70, 57, 68, 43, 8, 42, 29, 20, 50, 24, 46, 47, 89, 83, 18, 73, 28, 76, 37, 30, 67, 12, 10, 40, 32, 26, 53, 82, 19, 90, 88, 59, 14, 77, 31, 72, 17, 36, 74, 7, 66, 33, 22, 48, 56, 64, 75, 11, 6, 41, 21, 13, 79, 62, 84, 1, 54, 80, 2, 85, 58, 69, 39]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='z4sdxi', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='8BMNKY1', max_length=100),
        ),
    ]
