# Generated by Django 4.2.7 on 2023-11-30 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0048_ticket_pattern_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='claimrule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='pattern',
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[20, 43, 75, 88, 50, 12, 28, 89, 53, 13, 8, 71, 55, 7, 56, 72, 90, 79, 26, 74, 66, 11, 61, 76, 25, 70, 9, 32, 73, 34, 67, 14, 19, 58, 62, 35, 29, 33, 52, 60, 36, 40, 1, 10, 78, 41, 42, 16, 83, 39, 54, 24, 38, 4, 49, 87, 65, 63, 22, 59, 3, 46, 15, 48, 27, 68, 44, 82, 2, 21, 5, 45, 69, 81, 77, 47, 17, 37, 86, 51, 80, 23, 84, 57, 30, 6, 18, 64, 85, 31]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='ftj755', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='MEZOU47', max_length=100),
        ),
        migrations.CreateModel(
            name='BuyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now=True)),
                ('order_status', models.BooleanField(default=False)),
                ('order_price', models.CharField(max_length=200, null=True)),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('ticketid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambolaapp.ticket')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='claimrule',
            name='ticket',
        ),
    ]
