# Generated by Django 4.2.7 on 2023-11-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0049_alter_claimrule_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawrequest',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='ticket',
            name='pattern',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[9, 15, 78, 53, 4, 14, 48, 52, 16, 85, 21, 86, 83, 47, 19, 56, 66, 40, 22, 3, 31, 87, 84, 36, 12, 34, 88, 13, 73, 30, 2, 70, 11, 18, 61, 77, 51, 76, 64, 90, 50, 35, 57, 32, 38, 89, 75, 10, 72, 5, 24, 82, 65, 54, 26, 27, 45, 69, 44, 33, 39, 58, 59, 29, 28, 62, 7, 60, 1, 6, 81, 55, 37, 25, 80, 23, 67, 43, 63, 71, 20, 68, 17, 41, 46, 42, 49, 74, 79, 8]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='qqmt43', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='ZYTDS94', max_length=100),
        ),
        migrations.DeleteModel(
            name='BuyTicket',
        ),
    ]
