# Generated by Django 4.2.7 on 2023-11-30 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0050_remove_withdrawrequest_is_completed_ticket_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[58, 85, 60, 7, 29, 28, 79, 45, 50, 14, 5, 44, 48, 37, 27, 6, 89, 51, 12, 16, 35, 46, 65, 78, 43, 47, 2, 32, 90, 33, 57, 22, 71, 34, 87, 74, 52, 42, 59, 86, 19, 10, 80, 31, 82, 49, 67, 66, 38, 30, 54, 75, 62, 83, 72, 39, 53, 15, 88, 8, 77, 84, 4, 63, 24, 21, 69, 18, 73, 3, 70, 25, 41, 40, 81, 1, 56, 11, 20, 36, 23, 68, 13, 17, 76, 64, 55, 9, 26, 61]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='rdy5yl', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='F6WPF4H', max_length=100),
        ),
        migrations.CreateModel(
            name='BuyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now=True)),
                ('order_status', models.BooleanField(default=False)),
                ('order_price', models.CharField(max_length=200, null=True)),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('ticketid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambolaapp.ticket')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
