# Generated by Django 4.2.7 on 2023-12-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0051_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpandsupport',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[28, 73, 37, 60, 15, 79, 44, 2, 76, 55, 41, 54, 45, 9, 48, 20, 88, 64, 21, 6, 90, 34, 5, 23, 17, 13, 80, 70, 19, 77, 18, 33, 58, 42, 14, 3, 22, 57, 38, 82, 84, 47, 67, 8, 68, 52, 75, 12, 81, 71, 26, 36, 89, 62, 51, 10, 1, 32, 35, 69, 24, 11, 49, 59, 83, 4, 74, 43, 16, 85, 25, 7, 40, 63, 27, 86, 50, 46, 78, 56, 30, 53, 39, 61, 31, 29, 72, 87, 66, 65]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='4gc6to', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='4I3N577', max_length=100),
        ),
    ]
