# Generated by Django 4.2.7 on 2023-12-05 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0052_helpandsupport_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrule',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tambolaapp.ticket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[37, 88, 54, 32, 81, 79, 17, 55, 9, 87, 33, 46, 57, 12, 63, 77, 7, 31, 8, 80, 42, 41, 47, 70, 27, 51, 16, 76, 38, 13, 43, 44, 74, 35, 86, 5, 65, 78, 85, 82, 45, 24, 28, 68, 72, 20, 15, 73, 59, 22, 52, 30, 34, 61, 25, 58, 6, 84, 14, 56, 66, 53, 64, 39, 4, 10, 2, 83, 71, 67, 89, 18, 21, 40, 75, 11, 62, 3, 29, 1, 36, 49, 90, 60, 50, 26, 19, 48, 69, 23]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='2qhqaq', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='VI019KP', max_length=100),
        ),
    ]
