# Generated by Django 4.2.7 on 2023-12-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0053_claimrule_ticket_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[62, 22, 33, 25, 48, 24, 32, 37, 19, 40, 84, 60, 71, 75, 67, 28, 86, 30, 77, 74, 88, 23, 27, 80, 7, 89, 1, 90, 61, 78, 63, 21, 35, 6, 81, 29, 59, 15, 18, 69, 65, 44, 76, 47, 39, 54, 50, 58, 85, 64, 56, 26, 12, 68, 41, 51, 36, 38, 57, 14, 82, 87, 2, 31, 3, 45, 17, 83, 5, 4, 72, 49, 52, 10, 66, 8, 46, 34, 20, 16, 70, 43, 11, 53, 9, 55, 13, 73, 79, 42]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='glmc1q', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='T39CNGU', max_length=100),
        ),
        migrations.CreateModel(
            name='GameCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_array', models.JSONField(default=[])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tambolaapp.newgame')),
            ],
        ),
    ]
