# Generated by Django 4.2.7 on 2023-12-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0054_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_rule',
            old_name='name',
            new_name='rule',
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[63, 39, 31, 11, 2, 22, 6, 21, 5, 60, 59, 79, 33, 9, 14, 86, 67, 43, 81, 23, 12, 34, 68, 66, 38, 36, 44, 7, 54, 90, 27, 77, 37, 71, 49, 80, 35, 13, 48, 56, 16, 30, 24, 40, 75, 1, 26, 47, 61, 84, 8, 32, 42, 15, 87, 65, 3, 41, 29, 89, 85, 82, 76, 50, 45, 88, 55, 53, 52, 64, 83, 4, 18, 10, 72, 25, 17, 69, 20, 19, 62, 51, 57, 70, 28, 74, 78, 73, 58, 46]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='290chc', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='ZZ7T6A0', max_length=100),
        ),
    ]
