# Generated by Django 4.2.7 on 2023-12-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0055_rename_name_game_rule_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[45, 73, 33, 69, 43, 26, 12, 52, 80, 39, 40, 56, 62, 1, 18, 50, 44, 57, 81, 75, 77, 8, 68, 76, 19, 82, 90, 22, 38, 32, 65, 25, 9, 86, 48, 31, 15, 7, 20, 2, 13, 63, 58, 3, 6, 21, 5, 16, 83, 24, 34, 84, 23, 27, 17, 10, 41, 49, 72, 70, 28, 11, 71, 60, 55, 67, 29, 61, 66, 14, 87, 47, 4, 36, 59, 78, 74, 85, 51, 42, 35, 89, 53, 30, 88, 79, 64, 37, 46, 54]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='pv60ld', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='27BNVDG', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='claimrule',
            unique_together={('rule', 'ticket')},
        ),
    ]
