# Generated by Django 4.2.7 on 2023-12-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tambolaapp', '0056_alter_newgame_game_counter_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='claimrule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='game_counter',
            field=models.JSONField(default=[10, 4, 16, 7, 79, 88, 32, 53, 68, 25, 14, 74, 38, 66, 8, 13, 78, 81, 36, 57, 80, 73, 56, 6, 62, 71, 59, 82, 67, 87, 12, 54, 42, 40, 21, 33, 41, 5, 72, 51, 90, 55, 39, 61, 60, 48, 26, 2, 64, 52, 83, 28, 46, 31, 89, 75, 77, 22, 86, 85, 3, 1, 34, 11, 18, 76, 65, 20, 35, 29, 70, 69, 17, 9, 30, 27, 24, 49, 15, 19, 45, 58, 84, 47, 50, 37, 43, 23, 44, 63]),
        ),
        migrations.AlterField(
            model_name='newgame',
            name='private_code',
            field=models.CharField(default='1wi2li', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_code',
            field=models.CharField(default='BZ6Y1V7', max_length=100),
        ),
    ]
